### ISSUE TITLE
UniqueID changes between tags fired on Container Loaded vs DataLayer Loaded

### ISSUE THREAD

**Issue by JimboHamez** [stape-io/unique-event-id-variable#1]
Hi Team,

I am using this template to generate a UniqueID to deduplicate Facebook Pixel vs Google Tag Manager Server Side Conversion API for each ecommerce message Facebook requires to track users on our website.  What I noticed in both Facebook Event Manager and Tag Assistant was the deduplication parameter i.e. the eventID generated by this template was different between Facebook Pixel and the GA4 message sent to the GTM server.

Tag Assistant showed the eventID between the FB Pageview and the GA4 Pageview had similar values however where not exactly the same generally the GA4 Pageview showed a longer string of numbers.  The other pertinent piece of information is that the FB Pixel is fired when the Container is loaded and the GA4 tag is fired when the dataLayer is loaded.

On reviewing your code and confirmed with testing is the following code adds the gtm:uniqueEventId to the UniqueID being generated.  In doing so the string produced by the template cannot be reliably used for deduplication of Facebook events.

return getBrowserId() + '_' + getPageLoadId() + getGtmUniqueEventId();

For the time being I have removed the "+ getGtmUniqueEventId()" for the template and the string produced is now exactly the same, as proven by testing.

Cheers,
Jim

**Comment by Bukashk0zzz** [comment]
Hi,

This variable generates a unique event id.
If you use trigger group or tag sequencing, this will generate different IDs for each sequence.

If you remove getGtmUniqueEventId, then this variable will become unique per page, not per event.

More info https://community.stape.io/t/the-curious-case-of-the-view-item-event-on-server-side-gtm/600/3
